FROM debian:bullseye AS builder

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /workdir

RUN apt update && apt -y install git make build-essential

RUN git clone --recursive https://github.com/RediSearch/RediSearch.git

RUN cd RediSearch && make setup && make build


FROM python:3.11

ENV DEBIAN_FRONTEND=noninteractive
ARG S6_OVERLAY_VERSION=3.1.0.1

# Install redis
RUN apt update && apt -y install vim redis-server chromium-driver chromium cron && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /workdir/RediSearch/bin/linux-x64-release/search/redisearch.so /usr/lib/redisearch.so

WORKDIR /app

COPY requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

COPY docker/etc /etc/

COPY docker/bin /usr/bin/

COPY autogpt/ /app/autogpt

COPY scripts/ /app/scripts

COPY data_ingestion.py /app/

RUN git clone https://github.com/Significant-Gravitas/Auto-GPT-Plugins.git plugins

RUN echo "export TERM=screen-256color" >> /root/.bashrc

ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
RUN /bin/tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
RUN /bin/tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz
ENTRYPOINT ["/init"]
CMD ["bash"]
