FROM debian:bullseye AS builder

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /workdir

RUN apt update && apt -y install git make build-essential

RUN git clone --recursive https://github.com/RediSearch/RediSearch.git

RUN cd RediSearch && make setup && make build


FROM python:3.11

ENV DEBIAN_FRONTEND=noninteractive
ARG S6_OVERLAY_VERSION=3.1.0.1

# Install redis
RUN apt update && apt -y install redis-server && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /workdir/RediSearch/bin/linux-x64-release/search/redisearch.so /usr/lib/redisearch.so

COPY docker/etc /etc/

COPY docker/bin /usr/bin/

WORKDIR /app
COPY scripts/ /app

COPY requirements.txt /app
RUN pip install -r requirements.txt

#ENTRYPOINT ["python", "main.py"]
#CMD ["-h"]

ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
RUN /bin/tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
RUN /bin/tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz
ENTRYPOINT ["/init"]
CMD ["bash"]
